# Generated by Django 4.2.6 on 2023-11-26 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_alter_order_delivered_on_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 6, 32, 38, 658326, tzinfo=datetime.timezone.utc)),
        ),
    ]
