# Generated by Django 4.2.6 on 2023-11-26 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0016_review_user_alter_order_delivered_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 6, 53, 43, 209041, tzinfo=datetime.timezone.utc)),
        ),
    ]
