# Generated by Django 4.2.6 on 2023-11-26 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0018_reviewrating_alter_order_delivered_on_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 12, 37, 10, 139097, tzinfo=datetime.timezone.utc)),
        ),
    ]
