# Generated by Django 4.2.6 on 2023-11-26 16:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0020_alter_order_delivered_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Product.reviewrating'),
        ),
        migrations.AddField(
            model_name='order',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders22', to='Product.reviewrating'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 16, 31, 23, 731465, tzinfo=datetime.timezone.utc)),
        ),
    ]
