# Generated by Django 4.2.6 on 2023-11-26 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0021_order_comment_order_rating_alter_order_delivered_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rating',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 16, 59, 16, 558077, tzinfo=datetime.timezone.utc)),
        ),
    ]
