# Generated by Django 4.2.6 on 2023-11-27 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0023_alter_order_delivered_on_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 13, 43, 41, 731692, tzinfo=datetime.timezone.utc)),
        ),
    ]
