# Generated by Django 4.2.6 on 2023-11-28 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0032_alter_order_delivered_on_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 14, 29, 17, 675924, tzinfo=datetime.timezone.utc)),
        ),
    ]
