# Generated by Django 4.2.6 on 2023-12-03 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0041_alter_order_delivered_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 3, 16, 2, 12, 59454, tzinfo=datetime.timezone.utc)),
        ),
    ]
